version: 1
accounts:
- name: thepool
  coins:
   - 0usdc
   - 0usdt
   - 0dai
   - 0fdusd
   - 0weth
   - 0eth
   - 0steth
   - 0stake
   - 1000000000000sharetoken
  address: cosmos189z79vlskxjm4n54va5954xlh02ktca6djmct4
- name: virgie
  coins:
   - 2000000000usdc
   - 200000000stake
- name: servio
  coins:
  - 2000000000usdc
  - 1000000000stake
- name: carlos
  coins:
   - 2000000000usdc
   - 1000000000stake
- name: manuel
  coins:
   - 2000000000usdc
   - 1000000000stake
- name: orlando
  coins:
    - 100000000eth
    - 100000000weth
    - 1000000steth
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: servio
  coins:
  - 5000000usdc
  - 100000stake
validators:
- name: virgie
  bonded: 100000000stake
  client:
    chain-id: "simpleswap"
