version: 1
accounts:
- name: virgie
  coins:
  - 20000usdc
  - 200000000stake
- name: servio
  coins:
  - 10000usdc
  - 100000000stake
- name: carlos
  coins:
  - 10000usdc
  - 100000000stake
- name: manuel
  coins:
  - 10000usdc
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: servio
  coins:
  - 5usdc
  - 100000stake
validators:
- name: virgie
  bonded: 100000000stake
