// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package simpleswap

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_StableCoinsWhiteList           protoreflect.MessageDescriptor
	fd_StableCoinsWhiteList_index     protoreflect.FieldDescriptor
	fd_StableCoinsWhiteList_coin      protoreflect.FieldDescriptor
	fd_StableCoinsWhiteList_available protoreflect.FieldDescriptor
)

func init() {
	file_simpleswap_simpleswap_stable_coins_white_list_proto_init()
	md_StableCoinsWhiteList = File_simpleswap_simpleswap_stable_coins_white_list_proto.Messages().ByName("StableCoinsWhiteList")
	fd_StableCoinsWhiteList_index = md_StableCoinsWhiteList.Fields().ByName("index")
	fd_StableCoinsWhiteList_coin = md_StableCoinsWhiteList.Fields().ByName("coin")
	fd_StableCoinsWhiteList_available = md_StableCoinsWhiteList.Fields().ByName("available")
}

var _ protoreflect.Message = (*fastReflection_StableCoinsWhiteList)(nil)

type fastReflection_StableCoinsWhiteList StableCoinsWhiteList

func (x *StableCoinsWhiteList) ProtoReflect() protoreflect.Message {
	return (*fastReflection_StableCoinsWhiteList)(x)
}

func (x *StableCoinsWhiteList) slowProtoReflect() protoreflect.Message {
	mi := &file_simpleswap_simpleswap_stable_coins_white_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_StableCoinsWhiteList_messageType fastReflection_StableCoinsWhiteList_messageType
var _ protoreflect.MessageType = fastReflection_StableCoinsWhiteList_messageType{}

type fastReflection_StableCoinsWhiteList_messageType struct{}

func (x fastReflection_StableCoinsWhiteList_messageType) Zero() protoreflect.Message {
	return (*fastReflection_StableCoinsWhiteList)(nil)
}
func (x fastReflection_StableCoinsWhiteList_messageType) New() protoreflect.Message {
	return new(fastReflection_StableCoinsWhiteList)
}
func (x fastReflection_StableCoinsWhiteList_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_StableCoinsWhiteList
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_StableCoinsWhiteList) Descriptor() protoreflect.MessageDescriptor {
	return md_StableCoinsWhiteList
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_StableCoinsWhiteList) Type() protoreflect.MessageType {
	return _fastReflection_StableCoinsWhiteList_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_StableCoinsWhiteList) New() protoreflect.Message {
	return new(fastReflection_StableCoinsWhiteList)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_StableCoinsWhiteList) Interface() protoreflect.ProtoMessage {
	return (*StableCoinsWhiteList)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_StableCoinsWhiteList) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Index != "" {
		value := protoreflect.ValueOfString(x.Index)
		if !f(fd_StableCoinsWhiteList_index, value) {
			return
		}
	}
	if x.Coin != "" {
		value := protoreflect.ValueOfString(x.Coin)
		if !f(fd_StableCoinsWhiteList_coin, value) {
			return
		}
	}
	if x.Available != false {
		value := protoreflect.ValueOfBool(x.Available)
		if !f(fd_StableCoinsWhiteList_available, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_StableCoinsWhiteList) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "simpleswap.simpleswap.StableCoinsWhiteList.index":
		return x.Index != ""
	case "simpleswap.simpleswap.StableCoinsWhiteList.coin":
		return x.Coin != ""
	case "simpleswap.simpleswap.StableCoinsWhiteList.available":
		return x.Available != false
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: simpleswap.simpleswap.StableCoinsWhiteList"))
		}
		panic(fmt.Errorf("message simpleswap.simpleswap.StableCoinsWhiteList does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_StableCoinsWhiteList) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "simpleswap.simpleswap.StableCoinsWhiteList.index":
		x.Index = ""
	case "simpleswap.simpleswap.StableCoinsWhiteList.coin":
		x.Coin = ""
	case "simpleswap.simpleswap.StableCoinsWhiteList.available":
		x.Available = false
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: simpleswap.simpleswap.StableCoinsWhiteList"))
		}
		panic(fmt.Errorf("message simpleswap.simpleswap.StableCoinsWhiteList does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_StableCoinsWhiteList) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "simpleswap.simpleswap.StableCoinsWhiteList.index":
		value := x.Index
		return protoreflect.ValueOfString(value)
	case "simpleswap.simpleswap.StableCoinsWhiteList.coin":
		value := x.Coin
		return protoreflect.ValueOfString(value)
	case "simpleswap.simpleswap.StableCoinsWhiteList.available":
		value := x.Available
		return protoreflect.ValueOfBool(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: simpleswap.simpleswap.StableCoinsWhiteList"))
		}
		panic(fmt.Errorf("message simpleswap.simpleswap.StableCoinsWhiteList does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_StableCoinsWhiteList) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "simpleswap.simpleswap.StableCoinsWhiteList.index":
		x.Index = value.Interface().(string)
	case "simpleswap.simpleswap.StableCoinsWhiteList.coin":
		x.Coin = value.Interface().(string)
	case "simpleswap.simpleswap.StableCoinsWhiteList.available":
		x.Available = value.Bool()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: simpleswap.simpleswap.StableCoinsWhiteList"))
		}
		panic(fmt.Errorf("message simpleswap.simpleswap.StableCoinsWhiteList does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_StableCoinsWhiteList) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "simpleswap.simpleswap.StableCoinsWhiteList.index":
		panic(fmt.Errorf("field index of message simpleswap.simpleswap.StableCoinsWhiteList is not mutable"))
	case "simpleswap.simpleswap.StableCoinsWhiteList.coin":
		panic(fmt.Errorf("field coin of message simpleswap.simpleswap.StableCoinsWhiteList is not mutable"))
	case "simpleswap.simpleswap.StableCoinsWhiteList.available":
		panic(fmt.Errorf("field available of message simpleswap.simpleswap.StableCoinsWhiteList is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: simpleswap.simpleswap.StableCoinsWhiteList"))
		}
		panic(fmt.Errorf("message simpleswap.simpleswap.StableCoinsWhiteList does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_StableCoinsWhiteList) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "simpleswap.simpleswap.StableCoinsWhiteList.index":
		return protoreflect.ValueOfString("")
	case "simpleswap.simpleswap.StableCoinsWhiteList.coin":
		return protoreflect.ValueOfString("")
	case "simpleswap.simpleswap.StableCoinsWhiteList.available":
		return protoreflect.ValueOfBool(false)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: simpleswap.simpleswap.StableCoinsWhiteList"))
		}
		panic(fmt.Errorf("message simpleswap.simpleswap.StableCoinsWhiteList does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_StableCoinsWhiteList) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in simpleswap.simpleswap.StableCoinsWhiteList", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_StableCoinsWhiteList) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_StableCoinsWhiteList) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_StableCoinsWhiteList) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_StableCoinsWhiteList) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*StableCoinsWhiteList)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Index)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Coin)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Available {
			n += 2
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*StableCoinsWhiteList)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.Available {
			i--
			if x.Available {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x18
		}
		if len(x.Coin) > 0 {
			i -= len(x.Coin)
			copy(dAtA[i:], x.Coin)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Coin)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Index) > 0 {
			i -= len(x.Index)
			copy(dAtA[i:], x.Index)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Index)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*StableCoinsWhiteList)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: StableCoinsWhiteList: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: StableCoinsWhiteList: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Index = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Coin = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Available", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.Available = bool(v != 0)
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: simpleswap/simpleswap/stable_coins_white_list.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StableCoinsWhiteList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index     string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Coin      string `protobuf:"bytes,2,opt,name=coin,proto3" json:"coin,omitempty"`
	Available bool   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
}

func (x *StableCoinsWhiteList) Reset() {
	*x = StableCoinsWhiteList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simpleswap_simpleswap_stable_coins_white_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StableCoinsWhiteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StableCoinsWhiteList) ProtoMessage() {}

// Deprecated: Use StableCoinsWhiteList.ProtoReflect.Descriptor instead.
func (*StableCoinsWhiteList) Descriptor() ([]byte, []int) {
	return file_simpleswap_simpleswap_stable_coins_white_list_proto_rawDescGZIP(), []int{0}
}

func (x *StableCoinsWhiteList) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *StableCoinsWhiteList) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *StableCoinsWhiteList) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

var File_simpleswap_simpleswap_stable_coins_white_list_proto protoreflect.FileDescriptor

var file_simpleswap_simpleswap_stable_coins_white_list_proto_rawDesc = []byte{
	0x0a, 0x33, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x77, 0x61, 0x70, 0x2f, 0x73, 0x69, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x77, 0x61, 0x70, 0x2f, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x63,
	0x6f, 0x69, 0x6e, 0x73, 0x5f, 0x77, 0x68, 0x69, 0x74, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x77, 0x61,
	0x70, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x77, 0x61, 0x70, 0x22, 0x5e, 0x0a, 0x14,
	0x53, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x42, 0xd3, 0x01, 0x0a,
	0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x77, 0x61, 0x70, 0x2e,
	0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x77, 0x61, 0x70, 0x42, 0x19, 0x53, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x26, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73,
	0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x73, 0x77, 0x61, 0x70, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x77, 0x61, 0x70, 0xa2,
	0x02, 0x03, 0x53, 0x53, 0x58, 0xaa, 0x02, 0x15, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x77,
	0x61, 0x70, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x77, 0x61, 0x70, 0xca, 0x02, 0x15,
	0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x77, 0x61, 0x70, 0x5c, 0x53, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x73, 0x77, 0x61, 0x70, 0xe2, 0x02, 0x21, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x77,
	0x61, 0x70, 0x5c, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x77, 0x61, 0x70, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x16, 0x53, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x77, 0x61, 0x70, 0x3a, 0x3a, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x77,
	0x61, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_simpleswap_simpleswap_stable_coins_white_list_proto_rawDescOnce sync.Once
	file_simpleswap_simpleswap_stable_coins_white_list_proto_rawDescData = file_simpleswap_simpleswap_stable_coins_white_list_proto_rawDesc
)

func file_simpleswap_simpleswap_stable_coins_white_list_proto_rawDescGZIP() []byte {
	file_simpleswap_simpleswap_stable_coins_white_list_proto_rawDescOnce.Do(func() {
		file_simpleswap_simpleswap_stable_coins_white_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_simpleswap_simpleswap_stable_coins_white_list_proto_rawDescData)
	})
	return file_simpleswap_simpleswap_stable_coins_white_list_proto_rawDescData
}

var file_simpleswap_simpleswap_stable_coins_white_list_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_simpleswap_simpleswap_stable_coins_white_list_proto_goTypes = []interface{}{
	(*StableCoinsWhiteList)(nil), // 0: simpleswap.simpleswap.StableCoinsWhiteList
}
var file_simpleswap_simpleswap_stable_coins_white_list_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_simpleswap_simpleswap_stable_coins_white_list_proto_init() }
func file_simpleswap_simpleswap_stable_coins_white_list_proto_init() {
	if File_simpleswap_simpleswap_stable_coins_white_list_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_simpleswap_simpleswap_stable_coins_white_list_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StableCoinsWhiteList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_simpleswap_simpleswap_stable_coins_white_list_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_simpleswap_simpleswap_stable_coins_white_list_proto_goTypes,
		DependencyIndexes: file_simpleswap_simpleswap_stable_coins_white_list_proto_depIdxs,
		MessageInfos:      file_simpleswap_simpleswap_stable_coins_white_list_proto_msgTypes,
	}.Build()
	File_simpleswap_simpleswap_stable_coins_white_list_proto = out.File
	file_simpleswap_simpleswap_stable_coins_white_list_proto_rawDesc = nil
	file_simpleswap_simpleswap_stable_coins_white_list_proto_goTypes = nil
	file_simpleswap_simpleswap_stable_coins_white_list_proto_depIdxs = nil
}
